name: dox_annotation
description: Dox annotation for dox framework
version: 0.0.7
repository: https://github.com/necessarylion/dox_annotation
homepage: https://dartondox.dev

environment:
  sdk: '>=2.19.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
